---
title: "TEMPLATE: REPORT"
author: "Michael J. Braus"
date: "`r Sys.Date()`"
output: html_document
bibliography: /Users/michaeljbrauslap/Sync/references.bib
geometry: margin = 1.0in
header-includes:
  \usepackage{placeins}
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \usepackage{setspace}
  \usepackage{chngcntr}
  \setlength{\headheight}{23pt}
  \rhead{}
  \lfoot{REPORT}
  \rfoot{Braus, M. J.}
  \counterwithin{figure}{section}
  \counterwithin{table}{section}
  \usepackage{lineno}
  \linenumbers
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'rmd-output/',
                      echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev="png", dpi=300)
```

\renewcommand{\headrulewidth}{1.0pt}
\renewcommand{\footrulewidth}{0.4pt}

\fontencoding{T1}
\fontfamily{fvs}
\fontsize{11}{16}
\selectfont

\tableofcontents
\listoffigures
\listoftables

# Table

```{r}
wsstable <- read.csv("2020-02-19-field-sites-lat-long-table.csv", header=T)
knitr::kable(wsstable)
```